server {
    listen 8080;
    server_name 127.0.0.1;
    root ./www/;
    index index.html;
    client_max_body_size 2k;

    error_page 403 error_pages/403.html;
    error_page 404 error_pages/404.html;
    error_page 405 error_pages/405.html;
    error_page 413 error_pages/413.html;
    error_page 500 error_pages/500.html;

    location / {
        allow_methods GET POST DELETE;
        autoindex off;
    }

    location /uploads {
        allow_methods GET POST DELETE;
        autoindex on;
    }

    location /readonly {
        allow_methods GET;
        autoindex on;
    }

    location /error_pages {
        allow_methods GET;
        autoindex on;
    }

    location /go-home {
        return 302 /;
    }

    location /cgi-bin {
        allow_methods GET POST;
        autoindex off;
        cgi_path /usr/bin/python3;
        cgi_ext .py;
    }
}

server {
    listen 8081;
    server_name 127.0.0.1;
    root ./www/listener/;
    index index.html;
    client_max_body_size 2k;

       location / {
        allow_methods GET POST DELETE;
        autoindex off;
    }
}